# Generated by Django 2.1.2 on 2018-10-28 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20181028_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='application',
            field=models.CharField(default='NoApplication', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='context',
            field=models.CharField(default='NoContext', max_length=4096),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='reported_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 14, 37, 1, 800229)),
            preserve_default=False,
        ),
    ]
